#DB_DRIVER: org.postgresql.Driver
#DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
#DB_URL: jdbc:postgresql://localhost:5433/backend_db
#DB_USERNAME: user
#DB_PASSWORD: password
#DB_DDL_AUTO: update

ALLOWED_HOST_REGEX: "*.common.eu.corp.toyota.com:[8080,5173,443]"